export enum Path {
  Dashboard = '/dashboard',
  Home = '/home',
  HomeDashboard = '/home/dashboard',
  Thread = '/home/[id]',
  OrganizationOnboarding = '/onboarding',
  DataSourceConnections = '/connections',
  PlatformTenants = '/platform/tenants',
  TenantUsers = '/tenant/users',
  TenantWorkspaces = '/tenant/workspaces',
  GovernanceGlossary = '/governance/glossary',
  WorkspaceApprovals = '/workspace/approvals',
  Modeling = '/modeling',
  Onboarding = '/setup',
  OnboardingConnection = '/setup/connection',
  OnboardingModels = '/setup/models',
  OnboardingRelationships = '/setup/relationships',
  Knowledge = '/knowledge',
  KnowledgeQuestionSQLPairs = '/knowledge/question-sql-pairs',
  KnowledgeInstructions = '/knowledge/instructions',
  APIManagement = '/api-management',
  APIManagementHistory = '/api-management/history',
}
