apiVersion: apps/v1
kind: Deployment
metadata:
  name: wren-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wren-engine
  template:
    metadata:
      labels:
        app: wren-engine
    spec:
      volumes:
        - name: wren-data
          persistentVolumeClaim:
            claimName: wren-data-pvc
      containers:
        - name: wren-engine
          image: wren-toolkit-http:latest
          env:
            - name: WREN_TOOLKIT_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: wrenai-secrets
                  key: PG_URL
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: wren-data
              mountPath: /app/data
